### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by jayapal-vunet** [josephmachado/simple_dbt_project#5]
the password for postgress 'password1234' shows 'invalid password'. Pls help.

**Comment by josephmachado** [comment]
Hi @jayapal-vunet Could you please post screenshots of the result from running the following commands from your terminal?

1. `docker ps`
2. `pgcli -h localhost -U dbt -p 5432 -d dbt` and typing in `password1234` for the password

**Comment by jayapal-vunet** [comment]
Hey! Thank you for responding. The password issue is resolved. I ran into other errors. Please take a look at them and guide me. I have attached the screenshots. I have also run the 'tree' command to show u the contents.
![Screenshot from 2021-12-23 18-42-15](https://user-images.githubusercontent.com/86235236/147246943-a3e35ef6-188f-4827-a6ab-5cd693e81c6e.png)

![Screenshot from 2021-12-23 18-08-22](https://user-images.githubusercontent.com/86235236/147244055-3566a9d8-4a72-429e-ad0e-a9973e5854fa.png)
![Screenshot from 2021-12-23 18-29-31](https://user-images.githubusercontent.com/86235236/147244065-e4256eef-3f7a-4d2c-8fbe-3b03bf612a8c.png)

**Comment by josephmachado** [comment]
Hi @jayapal-vunet , did you run the following commands before `dbt run` ?

```
docker compose up -d
export DBT_PROFILES_DIR=$(pwd)
cd sde_dbt_tutorial
dbt snapshot
dbt run
```
The errors says tables are missing and the docker compose is responsible for setting up the tables with [this script](https://github.com/josephmachado/simple_dbt_project/blob/master/warehouse_setup/1_create_load_customer_order_state_table.sql)

**Comment by jayapal-vunet** [comment]
![Screenshot from 2021-12-28 17-31-08](https://user-images.githubusercontent.com/86235236/147564309-a890fe47-9b39-4fa0-85e1-83edec963f3e.png)

![Screenshot from 2021-12-28 18-53-07](https://user-images.githubusercontent.com/86235236/147570650-84bd8799-1caf-4d6a-81f9-e1766267b1f2.png)


Joseph, This is what I am getting. What can be the possible reasons and how can I resolve them?

**Comment by josephmachado** [comment]
this should be fixed, moved everything to a docker based approach
